---
name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: write
  actions: read

jobs:
  build:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Mdocs install and deploy
        run: |
          pip install mkdocs-material
          pip install -r requirements.txt
          mkdocs gh-deploy --force -s
